[project]
name = "covid-lung-atlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "scanpy[leiden]>=1.12",
    "scvi-tools>=1.4.1",
]
